USE [master]
GO

/****** Object:  Database [BookStore]    Script Date: 3/3/2024 7:11:21 PM ******/
CREATE DATABASE [BookStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SCHOOLWORK\MSSQL\DATA\BookStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BookStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SCHOOLWORK\MSSQL\DATA\BookStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BookStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BookStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BookStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BookStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BookStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [BookStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BookStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BookStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BookStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BookStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BookStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BookStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BookStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BookStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BookStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BookStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BookStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BookStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BookStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BookStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BookStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BookStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BookStore] SET RECOVERY FULL 
GO

ALTER DATABASE [BookStore] SET  MULTI_USER 
GO

ALTER DATABASE [BookStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BookStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BookStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BookStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BookStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BookStore] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BookStore] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BookStore] SET  READ_WRITE 
GO


